
<!DOCTYPE HTML>
<html>
<head>
    <title>Правитель к планетке</title>

</head>
<body>
<a href="/web/">Main</a>
<div>
    <form action="/web/lord-for-planet" method="post">

        <label for="lord_id">ID LORD:</label>
        <input type="text" id="lord_id" name="lord_id" >
        <br>

        <label for="planet_id"> ID PLANET: </label>
        <input type="text" id="planet_id" name="planet_id" >

        <input type="submit" value="Create">
    </form>
</div>


</body>
</html>